- id: arxiv:2306.11800 # dynaquant
  # image: https://ameya.info/images/project-list-thumbnails/dynaquant.png
- id: arxiv:2403.02310 # sarathi-serve
  image: https://ameya.info/images/project-list-thumbnails/sarathi-serve.png
- id: arxiv:2308.16369 # sarathi
  image: https://ameya.info/images/project-list-thumbnails/sarathi.png
- title:  "Vidur: A Large Scale Simulation Framework For LLM Inference"
  date: "2024-05-13"
  authors:
    - Amey Agrawal
    - Nitin Kedia
    - Jayashree Mohan
    - Ashish Panwar
    - Nipun Kwatra
    - Bhargav S. Gulavani
    - Ramachandran Ramjee
    - Alexey Tumanov
  publisher: "7th Annual Conference on Machine Learning Systems (MLSys’24), Santa Clara"
  image: https://ameya.info/images/project-list-thumbnails/vidur.png
- id: doi:10.1145/3394486.3403212 # holmes
  image: images/publication_thumbnails/holmes.png
  buttons:
    - type: video
      link: https://www.youtube.com/watch?v=qZ15gmRWj0s
    - type: code
      link: https://github.com/hsd1503/HOLMES
- id: arxiv:2104.12642 # compofa
  publisher: "Proc. of International Conference on Learning Representations (ICLR'21)"
  image: https://github.com/gatech-sysml/CompOFA/raw/main/figures/overview.png
  buttons:
    - type: video
      link: https://www.youtube.com/watch?v=DAi20CfDCfg
    - type: code
      link: https://github.com/gatech-sysml/CompOFA
- id: doi:10.1109/MM.2023.3317243 # peyman micro'23
  image: https://jianmingtong.github.io/images/sushi_micro.png
- id: arxiv:2306.17266 # sushi
  publisher: "Proc. of Sixth Conference on Machine Learning and Systems (MLSys'23)"
  image: https://jianmingtong.github.io/images/sushi.png
  buttons:
    - type: slides
      link: https://mlsys.org/media/mlsys-2023/Slides/2481.pdf
- id: arxiv:2210.15056 # unfoldml
  publisher: "Proc. of 36'th Conference on Neural Information Processing Systems (NeurIPS'22)"
  image: images/publication_thumbnails/unfoldml.png
- id: arxiv:2301.10879 # superfed
  image: images/publication_thumbnails/superfed.png
- title:  "Harmonica: Hybrid Accelerator to Overcome Imperfections of Mixed-signal DNN Accelerators" # harmonica
  date: "2024-05-27"
  authors:
    - Payman Behnam
    - Uday Kamal
    - A. Shafiee
    - Alexey Tumanov
    - Saibal Mukhopadhyay
  publisher: "Proc. 38'th IEEE International Parallel and Distributed Processing Symposium (IPDPS'24)"
  image: images/publication_thumbnails/harmonica.png
- id: arxiv:2312.16733 # superserve
  image: images/publication_thumbnails/superserve.png
- title: "TransEHR: Self-Supervised Transformer for Clinical Time Series Data" # TransEHR
  authors:
    - Yanbo Xu
    - Shangqing Xu
    - Manav Ramprassad
    - Alexey Tumanov
    - Chao Zhang
  publisher: "Proc. of Machine Learning for Health (ML4H'23)"
  date: "2023-12-10"
  image: images/publication_thumbnails/transehr.png
- id: arxiv:2310.15938 # abkd
  image: images/publication_thumbnails/abkd.png
- title: "Signed-Binarization: Unlocking Efficiency Through Repetition-Sparsity Trade-Off"
  authors:
    - Sachit Kuhar
    - Alexey Tumanov
    - Judy Hoffman
  date: "2023-06-01"
  publisher: "Proc. of 3rd On-Device Intelligence Workshop, Machine Learning and Systems (MLSys'23)"
  image: images/publication_thumbnails/signed-binary.png
  link: https://arxiv.org/pdf/2211.13838
- id: arxiv:2307.01292 # psml
  image: images/publication_thumbnails/psml.png
- title: "Enabling Real-time DNN Switching via Weight-Sharing"
  authors:
  - Jianming Tong
  - Yangyu Chen
  - Yue Pan
  - Abhimanyu Bambhaniya
  - Alind Khare
  - Taekyung Heo
  - Alexey Tumanov
  - Tushar Krishna
  link: https://par.nsf.gov/servlets/purl/10430210
  publisher: "Proc. of 2nd Architecture, Compiler, and System Support for Multi-model DNN Workloads Workshop"
  date: "2022-06-01"
  image: images/publication_thumbnails/isca_22.png
